name: eval_sweep_tft_qm9_2026-03-29_16-30-00
project: zatom
program: zatom/eval_fm.py

method: grid

metric: # Does not matter, as we are using sweep to run the experiment.
  goal: maximize
  name: test_qm9/valid_rate

parameters:
  ckpt_path:
    value: "${paths.root_dir}/checkpoints/zatom_1_joint_pretraining_paper_weights.ckpt"

  data:
    values: [joint]

  data.datamodule.datasets.mp20.proportion:
    value: 0.0

  date:
    value: "2026-03-29_16-30-00"

  experiment:
    value: eval

  model/architecture:
    values: [tft_80M]

  model.sampling.batch_size:
    value: 1000

  model.sampling.num_samples:
    value: 10000

  model.sampling.visualize:
    value: false

  model.architecture.pos_interpolant.white_noise_sampling_scale:
    values: [1.0, 10.0, 50.0, 100.0]

  model.sampling.steps:
    values: [10, 25, 50, 100, 250, 500, 1000]

  name:
    value: "eval_${hydra:runtime.choices.model/architecture}_noise-${model.architecture.pos_interpolant.white_noise_sampling_scale}_steps-${model.sampling.steps}_qm9"

  seed:
    value: 42

  tags:
    value: ["qm9", "fm", "eval", "sweep"]

command:
  - ${env}
  - HYDRA_FULL_ERROR=1
  - WANDB_START_METHOD=thread
  - python
  - ${program}
  - ${args_no_hyphens}
